//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GiftListEditor.Resources.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knockout.js examples.
        /// </summary>
        public static string APP_NAME {
            get {
                return ResourceManager.GetString("APP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working with Lists and Collections.
        /// </summary>
        public static string Collections_Menu {
            get {
                return ResourceManager.GetString("Collections_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computed Observables.
        /// </summary>
        public static string Computed_Menu {
            get {
                return ResourceManager.GetString("Computed_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courses.
        /// </summary>
        public static string Courses_Dropdown {
            get {
                return ResourceManager.GetString("Courses_Dropdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating custom bindings.
        /// </summary>
        public static string CustomBindings_Menu {
            get {
                return ResourceManager.GetString("CustomBindings_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading and saving data.
        /// </summary>
        public static string DataManipulation_Menu {
            get {
                return ResourceManager.GetString("DataManipulation_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo.
        /// </summary>
        public static string Demo_Menu {
            get {
                return ResourceManager.GetString("Demo_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examples.
        /// </summary>
        public static string Examples_Dropdown {
            get {
                return ResourceManager.GetString("Examples_Dropdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gift list editor.
        /// </summary>
        public static string Index_Menu {
            get {
                return ResourceManager.GetString("Index_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduction.
        /// </summary>
        public static string Introduction_Menu {
            get {
                return ResourceManager.GetString("Introduction_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting started with Knockout.
        /// </summary>
        public static string KnockoutGettingStarted_Menu {
            get {
                return ResourceManager.GetString("KnockoutGettingStarted_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building HTML5 and JavaScript Apps with MVVM and Knockout.
        /// </summary>
        public static string KnockoutMVVM_Dropdown {
            get {
                return ResourceManager.GetString("KnockoutMVVM_Dropdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observables.
        /// </summary>
        public static string Observable_Menu {
            get {
                return ResourceManager.GetString("Observable_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single page applications.
        /// </summary>
        public static string SPA_Menu {
            get {
                return ResourceManager.GetString("SPA_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No binding vs using Knockout.
        /// </summary>
        public static string WithoutDataBinding_Menu {
            get {
                return ResourceManager.GetString("WithoutDataBinding_Menu", resourceCulture);
            }
        }
    }
}
